# SPDX-License-Identifier: Apache-2.0
"""Server-VAD path tests for the Realtime WebSocket endpoint (M2).

Drives the full ``/v1/realtime`` route end-to-end with a real
silero-vad ONNX model and a fake ``Client`` so we can validate the VAD
state machine, multi-utterance segmentation, and auto-commit flow
without a GPU.
"""

from __future__ import annotations

import base64
import struct
from pathlib import Path
from typing import Any, AsyncIterator

import numpy as np
import pytest
import wave
from fastapi.testclient import TestClient

from sglang_omni.client import (
    AbortResult,
    CompletionStreamChunk,
)
from sglang_omni.client.types import AbortLevel
from sglang_omni.serve.openai_api import create_app
from sglang_omni.serve.realtime.audio_buffer import RealtimeAudioBuffer
from sglang_omni.serve.realtime.vad import (
    StreamingVAD,
    VADConfig,
    VADEvent,
    emits_for_test,
)


# ---------------------------------------------------------------------------
# Fakes
# ---------------------------------------------------------------------------


class FakeClient:
    def __init__(self, chunks_per_call: list[list[CompletionStreamChunk]]) -> None:
        self._chunks_per_call = list(chunks_per_call)
        self.calls = 0
        self.last_payloads: list[Any] = []
        self.aborted_ids: list[str] = []

    async def completion_stream(
        self, request: Any, *, request_id: str, audio_format: str = "wav"
    ) -> AsyncIterator[CompletionStreamChunk]:
        idx = self.calls
        self.calls += 1
        self.last_payloads.append(request.metadata.get("audios"))
        chunks = (
            self._chunks_per_call[idx]
            if idx < len(self._chunks_per_call)
            else self._chunks_per_call[-1]
        )
        for c in chunks:
            yield c

    async def abort(
        self, request_id: str, level: AbortLevel = AbortLevel.SOFT
    ) -> AbortResult:
        self.aborted_ids.append(request_id)
        return AbortResult(success=True, level_applied=level)

    def health(self) -> dict[str, Any]:
        return {"running": True}


def _read_wav_pcm16_16k(path: Path) -> bytes:
    with wave.open(str(path), "rb") as wf:
        assert wf.getframerate() == 16000
        assert wf.getsampwidth() == 2
        assert wf.getnchannels() == 1
        return wf.readframes(wf.getnframes())


def _b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def _silence_pcm(ms: int) -> bytes:
    n = 16000 * ms // 1000
    return struct.pack(f"<{n}h", *([0] * n))


# ---------------------------------------------------------------------------
# Pure VAD unit tests
# ---------------------------------------------------------------------------


def test_vad_emits_started_and_stopped_on_real_audio() -> None:
    fixture = Path("/tmp/realtime_fixture.wav")
    if not fixture.exists():
        pytest.skip(
            "Fixture /tmp/realtime_fixture.wav not present "
            "(generated by GPU validation step)."
        )
    pcm = _read_wav_pcm16_16k(fixture)

    emits = emits_for_test(pcm, threshold=0.5, silence_duration_ms=400)
    types = [e[0] for e in emits]
    starts = sum(1 for t in types if t == VADEvent.SPEECH_STARTED)
    stops = sum(1 for t in types if t == VADEvent.SPEECH_STOPPED)
    assert starts >= 1, f"expected ≥1 speech_started, got: {emits}"
    assert stops >= 1, f"expected ≥1 speech_stopped, got: {emits}"
    # Each stop must be preceded by a start.
    seen_open = 0
    for t, _ in emits:
        if t == VADEvent.SPEECH_STARTED:
            seen_open += 1
        elif t == VADEvent.SPEECH_STOPPED:
            assert seen_open > 0
            seen_open -= 1


def test_vad_silent_audio_emits_nothing() -> None:
    pcm = _silence_pcm(2000)  # 2 s of silence
    emits = emits_for_test(pcm, threshold=0.5, silence_duration_ms=400)
    assert emits == [], f"silence should not trigger VAD, got {emits}"


def test_vad_reset_clears_state() -> None:
    vad = StreamingVAD(VADConfig(threshold=0.5, silence_duration_ms=400))
    vad._is_speech = True  # type: ignore[attr-defined]
    vad._silence_run_samples = 999  # type: ignore[attr-defined]
    vad._samples_consumed = 5000  # type: ignore[attr-defined]
    vad.reset()
    assert vad._is_speech is False  # type: ignore[attr-defined]
    assert vad._silence_run_samples == 0  # type: ignore[attr-defined]


def test_audio_buffer_slice_and_tail() -> None:
    buf = RealtimeAudioBuffer()
    raw = _silence_pcm(100)  # 1600 samples
    buf.append_b64(_b64(raw))

    # Tail returns the last N bytes
    last_400 = buf.tail(400)
    assert len(last_400) == 400
    # Slice (0, 200) returns a valid WAV
    uri = buf.slice_to_wav_data_uri(start_byte=0, end_byte=200)
    assert uri and uri.startswith("data:audio/wav;base64,")
    decoded = base64.b64decode(uri.split(",", 1)[1])
    assert decoded[:4] == b"RIFF"


# ---------------------------------------------------------------------------
# WebSocket end-to-end via TestClient
# ---------------------------------------------------------------------------


def _make_app(
    chunks_per_call: list[list[CompletionStreamChunk]],
) -> tuple[Any, FakeClient]:
    fake = FakeClient(chunks_per_call)
    app = create_app(fake, model_name="qwen3-omni-test", enable_realtime=True)
    return app, fake


def test_ws_session_update_enables_server_vad() -> None:
    app, _ = _make_app([])
    with TestClient(app) as client:
        with client.websocket_connect("/v1/realtime") as ws:
            assert ws.receive_json()["type"] == "session.created"
            ws.send_json(
                {
                    "type": "session.update",
                    "session": {
                        "modalities": ["text"],
                        "input_audio_format": "pcm16",
                        "turn_detection": {
                            "type": "server_vad",
                            "threshold": 0.5,
                            "silence_duration_ms": 400,
                        },
                    },
                }
            )
            evt = ws.receive_json()
            assert evt["type"] == "session.updated"


def test_ws_session_update_rejects_semantic_vad() -> None:
    app, _ = _make_app([])
    with TestClient(app) as client:
        with client.websocket_connect("/v1/realtime") as ws:
            ws.receive_json()  # session.created
            ws.send_json(
                {
                    "type": "session.update",
                    "session": {"turn_detection": {"type": "semantic_vad"}},
                }
            )
            evt = ws.receive_json()
            assert evt["type"] == "error"
            assert "semantic_vad" in evt["error"]["message"]


def test_ws_server_vad_auto_commits_speech_segment() -> None:
    fixture = Path("/tmp/realtime_fixture.wav")
    if not fixture.exists():
        pytest.skip("Fixture /tmp/realtime_fixture.wav not present")

    pcm = _read_wav_pcm16_16k(fixture)
    # Append a 1s silence trailer so VAD sees a clear speech_stopped.
    pcm_padded = pcm + _silence_pcm(1500)

    chunks = [
        CompletionStreamChunk(request_id="x", text="hello", modality="text"),
        CompletionStreamChunk(
            request_id="x", text="", modality="text", finish_reason="stop"
        ),
    ]
    app, fake = _make_app([chunks, chunks, chunks])
    with TestClient(app) as client:
        with client.websocket_connect("/v1/realtime") as ws:
            ws.receive_json()  # session.created
            ws.send_json(
                {
                    "type": "session.update",
                    "session": {
                        "modalities": ["text"],
                        "input_audio_format": "pcm16",
                        "turn_detection": {
                            "type": "server_vad",
                            "threshold": 0.5,
                            "silence_duration_ms": 400,
                            "prefix_padding_ms": 200,
                        },
                    },
                }
            )
            assert ws.receive_json()["type"] == "session.updated"

            # Stream the audio in 200 ms chunks (6400 bytes each).
            chunk_bytes = 6400
            for i in range(0, len(pcm_padded), chunk_bytes):
                ws.send_json(
                    {
                        "type": "input_audio_buffer.append",
                        "audio": _b64(pcm_padded[i : i + chunk_bytes]),
                    }
                )

            collected: list[dict] = []
            for _ in range(40):
                evt = ws.receive_json()
                collected.append(evt)
                if evt["type"] == "conversation.item.input_audio_transcription.completed":
                    break

    types = [e["type"] for e in collected]
    assert "input_audio_buffer.speech_started" in types, types
    assert "input_audio_buffer.speech_stopped" in types, types
    assert "input_audio_buffer.committed" in types, types
    assert "conversation.item.input_audio_transcription.completed" in types, types

    # The fake client should have been called with a data URI carrying
    # the speech segment (not the full buffer + trailing silence).
    audio_payload = fake.last_payloads[-1]
    assert audio_payload and isinstance(audio_payload[0], str)
    assert audio_payload[0].startswith("data:audio/wav;base64,")
